import React, { useState } from 'react';
import Head from 'next/head';
import Background from '../src/components/Background/Background';
import Footer from '../src/components/Footer/Footer';
import UserInput from '../src/containers/UserInput/UserInput';
import YodaSpeak from '../src/containers/YodaSpeak/YodaSpeak';
import { QuoteContext } from '../src/contexts/QuoteContext';

export default function Home() {

  const [quote, setQuote] = useState(`Lost a planet,  master obiwan has.`)

  return (
    <div>
      <Head>
        <title>Talk like Yoda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <QuoteContext.Provider value={{ quote, setQuote }}>
        <YodaSpeak />
        <UserInput />
      </QuoteContext.Provider>
      <Footer />
    </div>
  )
}
